New Role Suggestions
Topkinsme/Color-Battle-Roles pull request #31
Opened 2021-06-06 18:53 UTC by TheEighthDeadlySin

Apparently renaming the branch deleted the pull request... At the moment, the only thing I have changed due to Luffy's thoughts is the Jester's respawn time (increased from 2 to 4). Sorry about the earlier pull request disappearing...

2021-06-06 19:19 UTC, TheEighthDeadlySin commented
I am not sure whether Jester should also have any attacking items, such as Bombs, that are planted on their target redirected to them. So for now, I have only included that Jester will only redirect abilities, and items used on their target will not be redirected (so Bombs, Poison, Antidote etc. will bypass this ability).

2021-06-07 04:02 UTC, Topkinsme requested changes
Warlord sounds good, but has the same problems Luffy earlier mentioned, with it just being killer but different. Also, do not have a "Winning Point" statement, just make it another point

Jester sounds good, but it should not be phase end, it should be that they pick a target during the day and it works for the entire next night.

Mage sounds good, But I recommend changing all instances of Basic Prot to weak prot, as it might be confusing if we add an actual basic prot status

Siege_warrior sounds good, however I feel like it should be a day action, as in the siege is planned during the day and executed during the night instead of it being instant.

Princess sounds good

Maybe we could drop sacrificial lamb's respawn, as it's only a 1-time thing.

2021-06-07 06:47 UTC, TheEighthDeadlySin commented
Okay, I shall implement the changes right now!

2021-06-07 06:55 UTC, TheEighthDeadlySin commented
Changes implemented:
Jester: Action is now performed during the day, any item or ability used throughout the night (includes immediate actions) on their target will instead be redirected to the Jester.
Mage: Renamed Basic Protection to Weak Protection.
Siege Warrior: Changed to action is performed during the day, and its effects are applied the following night.
Sacrificial Lamb: Decreased Respawn Time from 6 to 4.

2021-06-07 06:58 UTC, Topkinsme requested changes
Jester shouldn't redirect items, I only meant it should last the entire night instead of being an instant action

Everything else is good

2021-06-07 07:00 UTC, TheEighthDeadlySin commented
Okay, I will change Jester so only abilities (both immediate and end phase) are redirected. Items will not be affected.

2021-06-07 07:03 UTC, TheEighthDeadlySin commented
Removed Warlord

2021-06-07 08:14 UTC, TheEighthDeadlySin commented
I have added two Solo Chaos Role Suggestions: Gambler and Bounty Hunter. I have also checked to make sure all descriptions have been written in the third person.

2021-06-07 08:16 UTC, Topkinsme commented
I'd recommend you make a new pull req with all the solo roles like Warlord, Bounty Hunter, and gambler, since we're close to approving the other roles and we could implement the other roles and not worry about the solos for now

2021-06-07 10:00 UTC, TheEighthDeadlySin commented
Okay, I shall create a new role suggestion pull request containing the three solo chaos roles.

2021-06-07 10:16 UTC, TheEighthDeadlySin commented
Removed non-approved Solo Suggestions to a new pull request: https://github.com/Topkinsme/Color-Battle-Roles/pull/33

2021-06-07 10:18 UTC, Topkinsme commented on strong_power/jester
> +  Only abilities (noth immediate and end phase attacks) on their target will be redirected to the Jester.
"not" not "noth" typo

2021-06-07 10:19 UTC, Topkinsme approved these changes
Looks good to me, except that 1 typo

2021-06-07 10:21 UTC, Topkinsme commented
Also, you can change Sacrificial Limb respawn to 2 phases if you want, as Luffy suggested.

2021-06-07 10:24 UTC, TheEighthDeadlySin commented on strong_power/jester
> +  Only abilities (noth immediate and end phase attacks) on their target will be redirected to the Jester.
oops XD

2021-06-07 10:25 UTC, TheEighthDeadlySin commented on weak_power/sacrificial_lamb
> +- Respawns in 4 phases.
Okay.

2021-06-07 10:26 UTC, TheEighthDeadlySin commented on solo_chaos/bounty_hunter
> +- Every successful kill will give them $200 of a bounty reward.
The amount earned has to be from bounty killing, it does not count money earned from other sources, such as forge.

2021-06-07 10:27 UTC, TheEighthDeadlySin commented on weak_power/sacrificial_lamb
> +- Respawns in 4 phases.
I will decrease the respawn time to 2 phases.

2021-06-07 10:29 UTC, Topkinsme commented on strong_power/jester
> +  Items used on their target will not be affected.
Items don't work, so I don't think this applies

2021-06-07 10:30 UTC, Topkinsme commented on weak_power/sacrificial_lamb
> +- Respawns in 4 phases.
Agrred

2021-06-07 10:30 UTC, TheEighthDeadlySin commented on strong_power/jester
> +  Items used on their target will not be affected.
I put it in as a clarification (in case people thought Jester will also alter item usage).

2021-06-07 10:33 UTC, Topkinsme approved these changes
All good

2021-06-07 10:34 UTC, Topkinsme commented
I'm approving this pull request, this looks good to me.

2021-06-07 10:34 UTC, merged

2021-06-07 10:34 UTC, TheEighthDeadlySin commented on weak_power/sacrificial_lamb
> +- Respawns in 4 phases.
Done!