Create Worshipper
Topkinsme/Color-Battle-Roles pull request #54
Opened 2021-07-19 16:18 UTC by RogueAkira

2021-07-19 16:21 UTC, Topkinsme requested changes
The template is a bit off. You have mentioned some things which I feel like should be in the description of the pr itself.

Regarding the role itself, it's a decent idea, but might be too op. The insta respawn and 4 phase reduction along with the extension for the enemies could be brutal. However, I still think it could work.

Just fix the formatting when you can tho. Thanks!

2021-07-19 16:24 UTC, RogueAkira commented
> The template is a bit off. You have mentioned some things which I feel like should be in the description of the pr itself.
> 
> Regarding the role itself, it's a decent idea, but might be too op. The insta respawn and 4 phase reduction along with the extension for the enemies could be brutal. However, I still think it could work.
> 
> Just fix the formatting when you can tho. Thanks!

Thanks for your reply! I'm new to github and I will do the necessary things that are required...

2021-07-19 17:00 UTC, Topkinsme reviewed
Why is everything in quotes what

2021-07-20 08:52 UTC, TheEighthDeadlySin commented
I have a few questions about this role:
1. Will the prayers that require 2 phases to cast fail if the Worshipper dies during that time?
2. What happens if you want to extend someone's respawn time but they respawn right when you finish your incantation?
3. What will happen if the last King dies just as you finish your incantation to reduce your teammate's respawn time so that they instantly respawn?
4. Is each prayer only available once per game? If not, what are (if there are any) the cooldowns for each type of prayer?
5. If each prayer is a one time use, can you use multiple prayers at the same time?
6. If each prayer is a one time use and a specific prayer fails due to death or some other reason, will you lose that prayer?

2021-07-20 10:30 UTC, RogueAkira commented
> I have a few questions about this role:
> 
> 1. Will the prayers that require 2 phases to cast fail if the Worshipper dies during that time?
> 2. What happens if you want to extend someone's respawn time but they respawn right when you finish your incantation?
> 3. What will happen if the last King dies just as you finish your incantation to reduce your teammate's respawn time so that they instantly respawn?
> 4. Is each prayer only available once per game? If not, what are (if there are any) the cooldowns for each type of prayer?
> 5. If each prayer is a one time use, can you use multiple prayers at the same time?
> 6. If each prayer is a one time use and a specific prayer fails due to death or some other reason, will you lose that prayer?

The role Worshiper is similar to that of a Barricader but they alter the respawn phases instead of protecting.
Answers to your queries by order:
1.Yes the prayer fails and would be on hold and after they come back alive they could use it
2.Their respawn time increases and they will not respawn that phase
3.They instantly respawn
Question number 4,5 has been answered by the starting Barricader similarity sentence
6.Nope since the prayers are on hold and will finish once they come back alive 
Thanks for your time!

2021-07-20 10:31 UTC, RogueAkira commented
> Why is everything in quotes what

Dude u told me to do "-"

2021-07-20 10:32 UTC, Topkinsme commented
> > Why is everything in quotes what
> 
> Dude u told me to do "-"

I asked you to use hyphens (-) in front of the point, not quotes

2021-07-23 19:13 UTC, 12Metatron commented
should have a cooldown on each power, like mage

2021-07-30 06:01 UTC, 12Metatron commented on respawn_altering/Worshipper
> +"3.Demonic Incantation-could increase respawn phases by 2 for a enemy."
spacing inconsistency here.

2021-07-30 06:05 UTC, 12Metatron commented
2 small things.

1. the role files seems to always be lowercase, this one is upper case
2. needs to say what type of action this is (for action order purposes), in its own line near the bottom like the other roles. Personally, I suggest you say it's cast as a post-night action, which is what the the other respawn altering roles have it as

2022-05-30 14:35 UTC, RogueAkira reviewed
Changed some grammar and reworded some descriptions for ease of understanding.

2022-05-30 15:19 UTC, Topkinsme approved these changes
Still good, power levels open to debate

2022-05-30 16:17 UTC, merged